### ISSUE TITLE
error parsing json

### ISSUE THREAD

**Issue by ther3y3s** [obs-ai/obs-polyglot#2]
Hi, i have this error something when i try to use this plugin.

I use cloud closed captions to get captions and save them in a text source. Those are my settings:

![image](https://github.com/obs-ai/obs-polyglot/assets/35653733/640cb7cb-c36a-4542-b1a5-f648559780e9)

![image](https://github.com/obs-ai/obs-polyglot/assets/35653733/1391ce66-1f11-44f2-bdc8-71121d2ae948)

That's polygon settings:

![image](https://github.com/obs-ai/obs-polyglot/assets/35653733/8eea3058-f87f-4adc-9277-297a13fda393)

And those are url source settings: 
![image](https://github.com/obs-ai/obs-polyglot/assets/35653733/abddf9ec-9700-4a96-af03-8bb23ce593d3)

This is the body. I didn't find it on the page so i write it from youtube:
{"text":"{{input}}", "source_lang":"eng_Latn","target_lang":"ita_Latn"}

![image](https://github.com/obs-ai/obs-polyglot/assets/35653733/183234d2-b7d8-438e-ab36-8d23cd2eda31)

To test if this works or not i enable the preview on captions and start to talk. You can ses on top captions text, on bottom the translation:
![image](https://github.com/obs-ai/obs-polyglot/assets/35653733/ac8bec0e-42a2-4607-bd4c-0a74e5dfe262)

**Comment by royshil** [comment]
@ther3y3s thanks for the feedback
i think first step let's try the Test Request button
<img width="612" alt="Screenshot 2023-10-29 at 10 10 53 AM" src="https://github.com/obs-ai/obs-polyglot/assets/441170/90ce15a1-562d-4111-8b44-be5d5cf8ce2b">

And look for the `Request Body` section to see the JSON request is well formatted
<img width="612" alt="image" src="https://github.com/obs-ai/obs-polyglot/assets/441170/6b0712db-b0df-4a42-aa4a-2cc7160fe375">

**Comment by ther3y3s** [comment]
![image](https://github.com/obs-ai/obs-polyglot/assets/35653733/adea65fb-a9f0-468e-b8aa-93b466ac36bd)

But i notice after i stop to speak i have always the same output messagge:
![image](https://github.com/obs-ai/obs-polyglot/assets/35653733/ec60995b-e043-4279-9e86-55b22cf9aa2a)

andi i created another time the url source

**Comment by ther3y3s** [comment]
ok so i notice when i stop to talk and so captions disappears, the polyglot gets this output messagge (di cui si tratta) Instead of returning a blank value

**Comment by royshil** [comment]
@ther3y3s  yeah I think the model when it gets an empty text it has this "default value". It's common with LLMs to do this.

I think maybe if after {{input}} you put a "." it would be better

But the actual solution would be to never call polyglot in the first place, just clear the output... That's something I can work on.

**Comment by ther3y3s** [comment]
If i put a . there {"text":"{{input}}"." i get "error parsing json"

**Comment by royshil** [comment]
Try `{"text":"{{input}}.", ...}`

**Comment by ther3y3s** [comment]
always the "default value". So i think it's better just to disable the captions timeout.

But idk why i have always that problem
![image](https://github.com/obs-ai/obs-polyglot/assets/35653733/d5f69c99-b6cd-4a18-bf32-b72e65974e16)

**Comment by royshil** [comment]
This is peculiar since the JSON generally looks ok, maybe the newlines are a problem and need to be serialized to `\n`s but that's not available in obs-urlsource right now. I can work on that though.

**Comment by royshil** [comment]
I fixed this on URL Source.
The new version will fix this

**Comment by ther3y3s** [comment]
> I fixed this on URL Source. The new version will fix this

Oh wow thanks! 
Is alredy avaible or i can test it? Because i will use polyglot tomorrow

**Comment by royshil** [comment]
@ther3y3s you can grab this version https://github.com/occ-ai/obs-urlsource/actions/runs/6758096048#artifacts which will have this feature implemented
remember to add "Content-Type" -> "application/json" as a request header

**Comment by ther3y3s** [comment]
Thanks man. I tried but no releases :( and i don't know how i can do to get them

**Comment by royshil** [comment]
this is now implemented in the latest release of obs-urlsource
