### ISSUE TITLE
overload CPU

### ISSUE THREAD

**Issue by SweetRewenge** [obs-ai/obs-polyglot#4]
Hi, i noted some strange behavior when polyglot http server is started.
Check please attachments:

![Started](https://github.com/occ-ai/obs-polyglot/assets/23315053/fb6e4cfe-a76f-4aea-9eba-ea5bbce0a43d)
![Stop](https://github.com/occ-ai/obs-polyglot/assets/23315053/0c58fb0c-3f70-430d-8988-5ca24ae71c79)

How can i fix this issue?

**Comment by royshil** [comment]
@SweetRewenge are yu making requests to polyglot? or just starting the server?
please try the latest release as i've upgraded CT2 to a much newer version

**Comment by SweetRewenge** [comment]
> @SweetRewenge are yu making requests to polyglot? or just starting the server?
> 
> please try the latest release as i've upgraded CT2 to a much newer version

I will try it soon, thank you!

**Comment by royshil** [comment]
closing for now
